### ISSUE TITLE
It seems that the child not move with parent

### ISSUE THREAD

**Issue by happydpc** [dakom/shipyard-scenegraph#1]
I have tested the link. It doesn't work like the description.

**Comment by dakom** [comment]
@happydpc - I'm curious how you even found this repo :)

You're 100% right - it's early days, just getting started. Will update the README to say the current status

**Comment by happydpc** [comment]
> @happydpc - I'm curious how you even found this repo :)
> 
> You're 100% right - it's early days, just getting started. Will update the README to say the current status

I am just searching any SceneGraph crate for rust. Any recommend reference?

**Comment by dakom** [comment]
hmmm not sure, maybe check out [specs-hierarchy](https://github.com/rustgd/specs-hierarchy) and [legion-transform](https://github.com/AThilenius/legion_transform)

**Comment by dakom** [comment]
Children are moving with parent now :) Still early days and there is more optimization to do... but technically the demo works, so closing this issue for now
